// Generated by ingest/translate_ui.py — do not edit by hand.
// Each dictionary is loaded on demand, so the entry bundle carries none of them.
// A language absent here, or still loading, falls back to English.

import type { Dictionary } from './en'

type Loader = () => Promise<{ default?: Dictionary } & Record<string, unknown>>

export const loaders: Record<string, Loader> = {
  bn: () => import('./locales/bn'),
  gu: () => import('./locales/gu'),
  hi: () => import('./locales/hi'),
  kn: () => import('./locales/kn'),
  ml: () => import('./locales/ml'),
  mr: () => import('./locales/mr'),
  ta: () => import('./locales/ta'),
  te: () => import('./locales/te'),
}

/** Whether a language has a generated interface dictionary at all. */
export function hasDictionary(code: string): boolean {
  return code in loaders
}
