"""Generate the interface dictionaries from the English source.

The interface has around two hundred strings. Writing them by hand in eleven Indian languages would
mean shipping translations nobody on the team can check, in scripts most of us cannot read, into a
submission. Instead the English source is the single authority and the other languages are produced
by Sarvam's translation models — which is what they are built for — through the same identifier
guard the runtime uses, so "BIS" and any IS number survive.

The output is committed, so the interface needs no network at run time and a reviewer can read the
diff. Re-run it whenever `web/src/i18n/en.ts` changes.

    python ingest/translate_ui.py                  every language
    python ingest/translate_ui.py --only hi mr     just these
    python ingest/translate_ui.py --check          report coverage, translate nothing

A translated string is never trusted blindly: anything that comes back still containing a
placeholder, or that lost an identifier the English had, is dropped so the key falls back to English
rather than showing something broken.
"""

import argparse
import json
import re
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Dict, List

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.understand.language import LANGUAGES, LanguageHandler  # noqa: E402

SOURCE = ROOT / "web" / "src" / "i18n" / "en.ts"
OUT_DIR = ROOT / "web" / "src" / "i18n" / "locales"
INDEX = ROOT / "web" / "src" / "i18n" / "dictionaries.ts"

# Keys whose value is a proper noun or an identifier and must not be translated at all.
KEEP_AS_IS = {"app.name"}


def read_english() -> Dict[str, str]:
    """Pull the key/value pairs out of the TypeScript source.

    Parsing TypeScript with a regular expression is usually a mistake; it is safe here because the
    file is a flat object literal of string keys and string values that this project owns, and the
    alternative is adding a Node build step for one file.
    """
    text = SOURCE.read_text(encoding="utf-8")
    body = text[text.index("export const en = {"):]
    pairs = re.findall(r"^\s*'([^']+)':\s*\n?\s*'((?:[^'\\]|\\.)*)'", body, re.MULTILINE)
    return {key: value.replace("\\'", "'").replace("\\\\", "\\") for key, value in pairs}


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ")


def translate_language(handler: LanguageHandler, english: Dict[str, str], code: str) -> Dict[str, str]:
    keys = [key for key in english if key not in KEEP_AS_IS]
    values = [english[key] for key in keys]

    started = time.time()
    translated: List[str] = []
    # Four at a time. Eight earned rate limiting and left a third of the strings untranslated.
    with ThreadPoolExecutor(max_workers=4) as pool:
        for index, result in enumerate(pool.map(lambda v: handler.from_english(v, code), values)):
            translated.append(result)
            if (index + 1) % 50 == 0:
                print(f"    {index + 1}/{len(values)}", flush=True)

    out: Dict[str, str] = {}
    dropped: List[str] = []
    for key, source_text, result in zip(keys, values, translated):
        if not result or result == source_text:
            dropped.append(key)          # unchanged means the call failed; fall back to English
            continue
        if re.search(r"#\s*\d+\s*#", result):
            dropped.append(key)          # a placeholder survived into the output; do not ship it
            continue
        missing = [token for token in re.findall(r"\b(?:BIS|QCO|ISI|CRS|IS \d+)\b", source_text)
                   if token not in result]
        if missing:
            dropped.append(key)
            continue
        out[key] = result

    print(f"  {code}: {len(out)} translated, {len(dropped)} left in English "
          f"({time.time() - started:.0f}s)")
    if dropped:
        print(f"      fell back: {', '.join(dropped[:6])}{' …' if len(dropped) > 6 else ''}")
    return out


def write_locale(code: str, values: Dict[str, str]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by ingest/translate_ui.py — do not edit by hand.",
        "// English is the source of truth in ../en.ts; re-run the script after changing it.",
        "// Any key absent here falls back to English at run time.",
        "",
        "import type { Dictionary } from '../en'",
        "",
        f"export const {code}: Dictionary = {{",
    ]
    for key, value in values.items():
        lines.append(f"  '{key}': '{escape(value)}',")
    lines += ["}", ""]
    (OUT_DIR / f"{code}.ts").write_text("\n".join(lines), encoding="utf-8")


def write_index(codes: List[str]) -> None:
    lines = [
        "// Generated by ingest/translate_ui.py — do not edit by hand.",
        "",
        "import type { Dictionary } from './en'",
    ]
    for code in codes:
        lines.append(f"import {{ {code} }} from './locales/{code}'")
    lines += [
        "",
        "/** Every language but English, which is the source and needs no dictionary. */",
        "export const dictionaries: Record<string, Dictionary> = {",
    ]
    for code in codes:
        lines.append(f"  {code},")
    lines += ["}", ""]
    INDEX.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--only", nargs="*", help="language codes to build; default is all")
    parser.add_argument("--check", action="store_true", help="report coverage and exit")
    args = parser.parse_args()

    english = read_english()
    print(f"{len(english)} strings in {SOURCE.relative_to(ROOT)}")

    targets = [lang.code for lang in LANGUAGES if lang.code != "en"]
    if args.only:
        targets = [code for code in targets if code in args.only]

    if args.check:
        for code in targets:
            path = OUT_DIR / f"{code}.ts"
            if not path.exists():
                print(f"  {code}: not generated")
                continue
            count = len(re.findall(r"^\s*'[^']+':", path.read_text(encoding="utf-8"), re.MULTILINE))
            print(f"  {code}: {count}/{len(english)} ({count / len(english):.0%})")
        return

    handler = LanguageHandler()
    if not handler.available:
        raise SystemExit("No SARVAM_API_KEY configured, so nothing can be translated.")

    for code in targets:
        print(f"  {code} ...", flush=True)
        write_locale(code, translate_language(handler, english, code))

    write_index([lang.code for lang in LANGUAGES if lang.code != "en"])
    print(f"\nWrote {len(targets)} dictionaries to {OUT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
